name: DX Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    uses: gsmanivel/dx-workflows/.github/workflows/reusable-code-quality.yml@main
    with:
      ai_review: true